spring:
  datasource:
    url: jdbc:postgresql://${DB_PATH}/${DB_OPPORTUNITY_BANK}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    format-sql: true
hibernate:
  dialect: org.hibernate.dialect.HSQLDialect